# Generated by Django 5.2 for LifeGraph Day-1

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LifeNode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("raw_text", models.TextField(verbose_name="原始输入")),
                ("title", models.CharField(blank=True, default="", max_length=255, verbose_name="标题")),
                ("what", models.TextField(blank=True, default="", verbose_name="事件内容")),
                ("where_text", models.CharField(blank=True, default="", max_length=255, verbose_name="地点")),
                ("where_lat", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="纬度")),
                ("where_lng", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="经度")),
                ("occurred_at", models.DateTimeField(db_index=True, verbose_name="发生时间")),
                ("privacy", models.CharField(choices=[("private", "仅自己"), ("friends", "指定好友"), ("public", "公开")], db_index=True, default="private", max_length=20, verbose_name="隐私")),
                ("source_type", models.CharField(choices=[("text", "文本"), ("voice", "语音"), ("image", "图片"), ("video", "视频")], db_index=True, default="text", max_length=20, verbose_name="来源类型")),
                ("ai_parsed", models.BooleanField(default=False, verbose_name="AI 已解析")),
                ("parsed_payload", models.JSONField(blank=True, default=dict, verbose_name="解析结果")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="life_nodes", to=settings.AUTH_USER_MODEL, verbose_name="所有者")),
            ],
            options={
                "verbose_name": "LifeNode",
                "verbose_name_plural": "LifeNodes",
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="NodeParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_name", models.CharField(max_length=150, verbose_name="显示名称")),
                ("role", models.CharField(choices=[("participant", "参与者")], default="participant", max_length=30, verbose_name="角色")),
                ("status", models.CharField(choices=[("self", "自己"), ("pending", "待确认"), ("confirmed", "已确认"), ("rejected", "已拒绝")], db_index=True, default="self", max_length=20, verbose_name="状态")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("node", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participants", to="lifegraph.lifenode", verbose_name="节点")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="life_participations", to=settings.AUTH_USER_MODEL, verbose_name="用户")),
            ],
            options={
                "verbose_name": "NodeParticipant",
                "verbose_name_plural": "NodeParticipants",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="lifenode",
            index=models.Index(fields=["owner", "-occurred_at", "-id"], name="idx_lifenode_owner_time"),
        ),
        migrations.AddConstraint(
            model_name="nodeparticipant",
            constraint=models.UniqueConstraint(condition=models.Q(("user__isnull", False)), fields=("node", "user"), name="unique_lifenode_user_participant"),
        ),
    ]
